// Copyright (C) 2024 by original authors @ fluttericon.com, fontello.com
//This font was generated by FlutterIcon.com, which is derived from Fontello.
//
// To use this font, place it in your fonts/ directory and include the
// following in your pubspec.yaml
//
// flutter:
//   fonts:
//    - family:  CustomIcons
//      fonts:
//       - asset: fonts/CustomIcons.ttf
//
//
// * Font Awesome 5, Copyright (C) 2016 by Dave Gandy
//         Author:    Dave Gandy
//         License:   SIL (https://github.com/FortAwesome/Font-Awesome/blob/master/LICENSE.txt)
//         Homepage:  http://fortawesome.github.com/Font-Awesome/
//
import 'package:flutter/widgets.dart';

/// Flutter icons CustomIcons
class CustomIcons {
  CustomIcons._();

  static const _kFontFam = 'CustomIcons';
  static const String? _kFontPkg = null;

  static const IconData addSquare =
      IconData(0xe800, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData comment =
      IconData(0xe801, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heart =
      IconData(0xe802, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData home =
      IconData(0xe803, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData reels =
      IconData(0xe804, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData save =
      IconData(0xe805, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData send =
      IconData(0xe806, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData heartSolid =
      IconData(0xe807, fontFamily: _kFontFam, fontPackage: _kFontPkg);
  static const IconData messenger =
      IconData(0xf39f, fontFamily: _kFontFam, fontPackage: _kFontPkg);
}
